# Generated by Django 5.0.1 on 2024-01-24 20:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=255, verbose_name="Server Address"),
                ),
                (
                    "success_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Success Count"
                    ),
                ),
                (
                    "failure_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Failure Count"
                    ),
                ),
                (
                    "last_failure",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Failure Time"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Servers",
                "ordering": ["-created_at"],
            },
        ),
    ]
