# django-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clereyworker-deployment
spec:
  selector:
    matchLabels:
      app: clereyworker
  template:
    metadata:
      labels:
        app: clereyworker
    spec:
      containers:
      - name: clereyworker
        image: amirfazel/health:latest
        command: ["sh", "-c", "celery -A healthService worker --loglevel=info"]
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: db-credentials
        env:
        - name: DEBUG
          value: "0"
