# postgres-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.pg.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "ahorfazel" 
            - name: POSTGRES_PASSWORD
              value: {{ .Values.pg.database }}
            - name: POSTGRES_DB
              value: "ahorfazel"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
