apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  database: {{ .Values.postgresql.auth.database | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  