apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  database: {{ .Values.pg.database | b64enc | quote }}
  POSTGRES_USER: {{ .Values.pg.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.pg.password | b64enc | quote }}
  