apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  replication-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  postgres_password: {{ .Values.postgresql.auth.password | b64enc | quote }}