version: '3.8'

services:
  django:
    image: ahora-health:latest  # You might want to build this from a Dockerfile
    command: bash -c "python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app  # Mounts the project directory to the container
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - "DATABASE_URL=postgres://user:password@db:5432/dbname"
      - "CELERY_BROKER_URL=redis://redis:6379/0"
      - "CELERY_RESULT_BACKEND=redis://redis:6379/0"

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

  celeryworker:
    image:  ahora-health:latest
    command: celery -A your_project worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celerybeat:
    image:  ahora-health:latest
    command: celery -A your_project beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
      - celerybeat_data:/var/lib/celerybeat
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:
  celerybeat_data:
