version: '3.8'

services:
  django:
    image: health:latest 
    command: sh -c "python manage.py migrate && gunicorn --env DJANGO_SETTINGS_MODULE=healthService.settings healthService.wsgi:application"
    volumes:
      - .:/app  
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - "CELERY_BROKER_URL=redis://redis:6379/0"
      - "CELERY_RESULT_BACKEND=redis://redis:6379/0"
      - "DEBUG=0"
      - "POSTGRES_NAME=ahorfazel"
      - "POSTGRES_USER=ahorfazel"
      - "POSTGRES_PASSWORD=ahora-fazel"
      - "POSTGRES_HOST=postgres"
      - "POSTGRES_PORT=5432"
      - "TESTCYCLE=3600"


  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ahorfazel
      - POSTGRES_PASSWORD=ahorfazel
      - POSTGRES_DB=ahorfazel
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  celeryworker:
    image:  health:latest
    command: sh -c "celery -A healthService worker --loglevel=info"
    environment:
      - "CELERY_BROKER_URL=redis://redis:6379/0"
      - "CELERY_RESULT_BACKEND=redis://redis:6379/0"
      - "DEBUG=0"
      - "POSTGRES_NAME=ahorfazel"
      - "POSTGRES_USER=ahorfazel"
      - "POSTGRES_PASSWORD=ahora-fazel"
      - "POSTGRES_HOST=postgres"
      - "POSTGRES_PORT=5432"
      - "TESTCYCLE=3600" 
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celerybeat:
    image:  health:latest
    command: sh -c "celery -A healthService beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    environment:
      - "CELERY_BROKER_URL=redis://redis:6379/0"
      - "CELERY_RESULT_BACKEND=redis://redis:6379/0"
      - "DEBUG=0"
      - "POSTGRES_NAME=ahorfazel"
      - "POSTGRES_USER=ahorfazel"
      - "POSTGRES_PASSWORD=ahora-fazel"
      - "POSTGRES_HOST=postgres"
      - "POSTGRES_PORT=5432"
      - "TESTCYCLE=3600" 
    volumes:
      - .:/app
      - celerybeat_data:/var/lib/celerybeat
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:
  celerybeat_data:
