version: '3.8'

services:
  django:
    image: health:latest 
    command: sh -c "sleep 30 && python manage.py migrate && python manage.py runserver 0.0.0.0:80"
    volumes:
      - .:/app  
    ports:
      - "8000:80"
    depends_on:
      - postgres
      - redis
    environment:
      - "CELERY_BROKER_URL=redis://redis:6379/0"
      - "CELERY_RESULT_BACKEND=redis://redis:6379/0"
      - "DEBUG=0"
      - "POSTGRES_NAME=ahorfazel"
      - "POSTGRES_USER=ahorfazel"
      - "POSTGRES_PASSWORD=ahora-fazel"
      - "POSTGRES_HOST_READ=postgres"
      - "POSTGRES_HOST_WRITE=postgres"
      - "POSTGRES_PORT=5432"
      - "TESTCYCLE=3600" 


  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ahorfazel
      - POSTGRES_PASSWORD=ahora-fazel
      - POSTGRES_DB=ahorfazel
    ports:
      - 5432:5432


  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  celeryworker:
    image:  health:latest
    command: sh -c "sleep 40 && celery -A healthService worker --loglevel=info"
    environment:
      - "CELERY_BROKER_URL=redis://redis:6379/0"
      - "CELERY_RESULT_BACKEND=redis://redis:6379/0"
      - "DEBUG=0"
      - "POSTGRES_NAME=ahorfazel"
      - "POSTGRES_USER=ahorfazel"
      - "POSTGRES_PASSWORD=ahora-fazel"
      - "POSTGRES_HOST_READ=postgres"
      - "POSTGRES_HOST_WRITE=postgres"
      - "POSTGRES_PORT=5432"
      - "TESTCYCLE=3600" 
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  celerybeat:
    image:  health:latest
    command: sh -c "sleep 40 && celery -A healthService beat --loglevel=info"
    environment:
      - "CELERY_BROKER_URL=redis://redis:6379/0"
      - "CELERY_RESULT_BACKEND=redis://redis:6379/0"
      - "DEBUG=0"
      - "POSTGRES_NAME=ahorfazel"
      - "POSTGRES_USER=ahorfazel"
      - "POSTGRES_PASSWORD=ahora-fazel"
      - "POSTGRES_HOST_READ=postgres"
      - "POSTGRES_HOST_WRITE=postgres"
      - "POSTGRES_PORT=5432"
      - "TESTCYCLE=3600" 
    volumes:
      - .:/app
      - celerybeat_data:/var/lib/celerybeat
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
  celerybeat_data: