apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
        - name: celery-beat
          image: amirfazel/health:latest
          command:
            [
              "sh",
              "-c",
              "sleep 40 && celery -A healthService beat --loglevel=info",
            ]
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-credentials
