apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000  # این فیلد فقط برای نوع NodePort لازم است و باید در بازه‌ی مجاز قرار گیرد.
  type: LoadBalancer  # برای NodePort، این را به NodePort تغییر دهید.
