replicaCount: 1

image:
  repository: feri80/health
  pullPolicy: IfNotPresent
  tag: "2.0"

service:
  type: ClusterIP
  port: 80
  containerPort: 80

env:
  TIMECYCLE: 3600

postgresql: 
  architecture: replication
  replicaCount: 1 
  auth: 
    database: ahorfazel 
    username: ahorafazel
    password: ahora-fazel
  image: 
    registry: docker.io 
    repository: bitnami/postgresql 
    tag: "13.0.0-debian-10-r0" 
    pullPolicy: IfNotPresent


prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitors:
      - name: "health"
        selector:
          matchLabels:
            app: "health"
        endpoints:
          - port: "http"
            interval: "30s"

grafana:
  enabled: true
  adminPassword: "admin"
  service:
    type: LoadBalancer
