# postgres-primary-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres-primary
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    statefulset.kubernetes.io/pod-name: postgres-0