apiVersion: v1
kind: Service
metadata:
  name: postgres-primary
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    statefulset.kubernetes.io/pod-name: postgres-0